version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  m1:
    build:
      dockerfile: Dockerfile
      context: ./m1
    container_name: m1
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - "rabbitmq"
    environment:
      - MSG_QUEUE_URL=amqp://rabbitmq:5672/
      - PORT=3000
  m2:
    build:
      dockerfile: Dockerfile
      context: ./m2
    container_name: m2
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      - "rabbitmq"
    environment:
      - MSG_QUEUE_URL=amqp://rabbitmq:5672/
      - PORT=3001
networks:
  default:
    driver: bridge
